# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory inside the container
# WORKDIR /usr/src/app
# should be where pckage.json is, wich is, relatively to ./client, ./ so no change
# Set the working directory inside the container
# i dont know
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies (excluding dev dependencies)
RUN npm ci --omit=dev

# Copy all files from the current directory to the working directory
COPY . .

# RUN npx prisma generate
# RUN npx prisma migrate dev --name init
# RUN npx prisma db push

# Expose the port your app runs on
EXPOSE 3000

# Command to start your application
# CMD ["npm", "start"]
CMD ["npm", "run", "dev"]
