version: '3'

services:
  fastapi:
    container_name: fastapi_container_default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose FastAPI server port
    volumes:
      - .:/app
